name: Build/release

on:
  push

jobs:
  release:
    runs-on: self-hosted
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'
      - name: Get Build Number
        if: matrix.os == 'ubuntu-latest'
        id: build_number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/workflows/linux.yml
        with:
          build_number: ${{ steps.build_number.outputs.build_number }}