name: Build/release

on: push

jobs:
  release:
    runs-on: self-hosted
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 21.7.1
                
      - if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Running Linux specific steps"
        npm i
        npx update-browserslist-db@latest
        npm audit fix --force
        if [ $? -ne 0 ]; then
          echo "npm audit fix --force failed. Trying manual updates..."
          # Manually update dependencies in package.json
          npm install
          # Resolve any compatibility issues or make necessary code changes
        fi
        npm run dist-linux
        echo "APPIMAGE_FILE=$(ls dist/*.AppImage)" >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
      
      
      - name: Get Build Number
        if: matrix.os == 'ubuntu-latest'
        id: build_number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: matrix.os == 'ubuntu-latest'
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build_number.outputs.build_number }}
          release_name: Release-${{ steps.build_number.outputs.build_number }}
          draft: false
          prerelease: false
      
 
